# Generated by Django 2.1.8 on 2019-10-06 11:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryGroup',
        ),
        migrations.DeleteModel(
            name='DeliveryService',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='deliverylist',
            name='notion',
        ),
        migrations.AddField(
            model_name='deliverylist',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverylist',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
